var quests = [
	"Unbound",
	"Before the Storm",
	"Bleak Falls Barrow",
	"Dragon Rising",
	"The Way of the Voice",
	"The Horn of Jurgen Windcaller",
	"A Blade in the Dark",
	"Diplomatic Immunity",
	"A Cornered Rat",
	"Alduin's Wall",
	"The Throat of the World",
	"Elder Knowledge",
	"Alduin's Bane",
	"The Fallen",
	"Season Unending",
	"Paarthurnax",
	"Season Unending",
	"The World-Eater's Eyrie",
	"Sovngarde",
	"Dragonslayer",
	"Take Up Arms",
	"Proving Honor",
	"The Silver Hand",
	"Blood's Honor",
	"Purity of Revenge",
	"Glory of the Dead",
	"Initial Wave: Animal Extermination",
	"Initial Wave: Animal Extermination",
	"Initial Wave: Hired Muscle",
	"Initial Wave: Trouble in Skyrim",
	"Initial Wave: Family Heirloom",
	"Initial Wave: Escaped Criminal",
	"Initial Wave: Rescue Mission",
	"Second Wave: Striking the Heart",
	"Second Wave: Stealing Plans",
	"Second Wave: Retrieval",
	"Final Wave: Totems of Hircine",
	"Final Wave: Purity",
	"Final WAve: Dragon Seekers",
	"First Lessons",
	"Under Saarthal",
	"Hitting the Books",
	"Good Intentions",
	"Revealing the Unseen",
	"Containment",
	"The Staff of Magnus",
	"The Eye of Magnus",
	"Rejoining the College",
	"Tolfdir's Alembic",
	"Out of Balance",
	"Enchanting Pick-Up",
	"Restocking Soul Gems",
	"Fetch a book for Urag Gro-Shub",
	"Shalidor's Insights",
	"The Atronach Forge",
	"Forgotten Names",
	"Aftershock",
	"Rogue Wizard",
	"Arniel's Endeavors",
	"Filling Soul Gems",
	"Brelyna's Practice",
	"J'Zargo's Experiment",
	"Onmund's Request",
	"Destruction Ritual Spell",
	"Illusion Ritual Spell",
	"Conjuration Ritual Spell",
	"Restoration Ritual Spell",
	"Alteration Ritual Spell",
	"A Chance Arrangement",
	"Taking Care of Business",
	"Loud and Clear",
	"Dampened Spirits",
	"Scoundrel's Folly",
	"Speaking with Silence",
	"Hard Answers",
	"The Pursuit",
	"Trinity Restored",
	"Blindsighted",
	"Darkness Returns",
	"No Stone Unturned",
	"Reparations",
	"Shadowmarks",
	"Moon Sugar Rush",
	"Armor Exchange",
	"The Litany of Larceny",
	"Silver Lining",
	"The Dainty Sload",
	"Imitation Amnesty",
	"Summerset Shadows",
	"Under New Management",
	"The Bedlam Job",
	"The Fishing Job",
	"The Numbers Job",
	"The Burglary Job",
	"The Shill Job",
	"The Sweep Job",
	"The Heist Job",
	"Delayed Burial",
	"Innocence Lost",
	"With Friends Like These...",
	"Sanctuary",
	"Sentenced to Death",
	"Whispers in the Dark",
	"The Silence has been Broken",
	"Bound Until Death",
	"Breaching Security",
	"The Cure for Madness",
	"Recipe for Disaster",
	"To Kill and Empire",
	"Death Incarnate",
	"Hail Sithis!",
	"Part 1 - Kill Narfi",
	"Part 2 - Kill Beitild",
	"Part 3 - Kill Ennodius Papius",
	"Part 4 - Kill Hern",
	"Part 5 - Kill Lurbuk",
	"Part 6 - Kill Deekus",
	"Part 7 - Kill Ma'randru-jo",
	"Part 8 - Kill Anoriath",
	"Part 9 - Kill Agnis",
	"Part 10 - Kill Maluril",
	"Part 11 - Kill Helvard",
	"Part 12 - Kill Safia",
	"Destroy the Dark Brotherhood!",
	"Where You Hang Your Enemy's Head",
	"Honor Thy Family",
	"The Feeble Fortune",
	"Welcome to the Brotherhood",
	"Cicero's Return",
	"The Dark Brotherhood Forever!",
	"Joining the Legion",
	"The Jagged Crown",
	"Message to Whiterun",
	"Defense of Whiterun",
	"Reunification of Skyrim - A False Front",
	"Reunification of Skyrim - The Battle for Fort Dunstad",
	"Reunification of Skyrim - Compelling Tribute",
	"Reunification of Skyrim - The Battle for Fort Greenwall",
	"Reunification of Skyrim - Rescue from Fort Kastav",
	"Reunification of Skyrim - The Battle for Fort Amol",
	"Reunification of Skyrim - Battle for Windhelm",
	"Joining the Stormcloaks",
	"The Jagged Crown",
	"Message to Whiterun",
	"Battle for Whiterun",
	"Liberation of Skyrim - Rescue From Fort Neugrad",
	"Liberation of Skyrim - Compelling Tribute",
	"Liberation of Skyrim - The Battle for Fort Sungard",
	"Liberation of Skyrim - A False Front",
	"Liberation of Skyrim - The Battle for Fort Snowhawk",
	"Liberation of Skyrim - The Battle for Fort Hraggstad",
	"Liberation of Skyrim - Battle for Solitude",
	"The Black Star",
	"Boethiah's Calling",
	"A Daedra's Best Friend",
	"Discerning the Transmundane",
	"I'll Met by Moonlight",
	"The Cursed Tribe",
	"Pieces of the Past",
	"The Whispering Door",
	"The Break of Dawn",
	"The House of Horrors",
	"The Taste of Death",
	"Darkness Returns",
	"The Only Cure",
	"A Night to Remember",
	"The Mind of Madness",
	"Waking Nightmare",
	"Word Wall Revelations",
	"Meditations on Words of Power",
	"Rebuilding the Blades",
	"Dragonslayer's Blessing",
	"Dragon Research",
	"Dragon Hunting",
	"Tending the Flames",
	"Finn's Lute",
	"Pantea's Flute",
	"Rjorn's Drum",
	"The Heart of Dibella",
	"The Book of Love",
	"The Blessings of Nature",
	"Blood on the Ice",
	"Forbidden Legend",
	"The Forsworn Conspiracy",
	"No One Escapes Cidhna Mine",
	"The Golden Claw",
	"In My Time of Need",
	"Kyne's Sacred Trials",
	"Laid to Rest",
	"Lights Out!",
	"The Man Who Cried Wolf",
	"The Wolf Queen Awakened",
	"Missing in Action",
	"Promises to Keep",
	"A Return to Your Roots",
	"Rise in the East",
	"Rising at Dawn",
	"Unfathomable Depths",
	"The White Phial",
	"Repairing the Phial",
	"Captured Critters",
	"The Forgemaster's Fingers",
	"The Great Skyrim Treasure Hunt",
	"Masks of the Dragon Priests",
	"Angarvunde: Medresi Dran and the Wandering Road",
	"Ansilvund: A Love Beyond Death",
	"Angi's Camp: Composure, Speed, and Precision",
	"Bard's Leap Summit: Leap Before You Look",
	"Blind Cliff Cave: Melka and Petra The Affairs of Hagravens",
	"Darklight Tower: Repentance",
	"Forelhost: Siege on the Dragon Cult",
	"Frostflow Lighthouse: What Lies Beneath",
	"Frostmere Crypt: The Pale Lady",
	"High Gate Ruins: A Scroll for Anska",
	"Hillgrund's Tomb: Ancestral Worship",
	"Mistwatch: Forgetting About Fjola",
	"Moss Mother Cavern: Hunter and Hunted",
	"Nchland-Zel: The Lost Expedition",
	"Nilheim: The Nilheim Scam - Telrav's Request",
	"Ragnvald: Otar's Mad Guardians",
	"Rebel's Cairn: The Legend of Red Eagle",
	"Robber's Gorge: Robber's Gorge",
	"Shipwreck: Trius' Trinket",
	"Shroud Hearth Barrow: Wilhelm's Specter - Lifting the Shroud",
	"Shroud Hearth Barrow Location Code = shroudhearthbarrow01",
	"Sleeping Tree Camp: The Secret at the Sleeping Tree",
	"Southfringe Sanctum: The Savior of Selveni Nethri",
	"Treva's Watch: Infiltration",
	"Valthume: Evil in Waiting",
	"Volunruud: Silenced Tongues",
	"YngolBarrow: Ashore in a Sea of Ghosts"
];